//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("SaleModel", "FK_cTietHDon_HoaDon", "HoaDon", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SaleManagement.DAL.HoaDon), "ChiTietHoaDon", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SaleManagement.DAL.ChiTietHoaDon), true)]
[assembly: EdmRelationshipAttribute("SaleModel", "FK_cTietHDon_lKien", "LinhKien", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SaleManagement.DAL.LinhKien), "ChiTietHoaDon", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SaleManagement.DAL.ChiTietHoaDon), true)]
[assembly: EdmRelationshipAttribute("SaleModel", "FK_cTietPNhap_lKien", "LinhKien", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SaleManagement.DAL.LinhKien), "ChiTietPhieuNhap", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SaleManagement.DAL.ChiTietPhieuNhap), true)]
[assembly: EdmRelationshipAttribute("SaleModel", "FK_cTietPNhap_PhieuNhap", "PhieuNhap", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SaleManagement.DAL.PhieuNhap), "ChiTietPhieuNhap", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SaleManagement.DAL.ChiTietPhieuNhap), true)]
[assembly: EdmRelationshipAttribute("SaleModel", "FK_HoaDon_kHang", "KhachHang", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SaleManagement.DAL.KhachHang), "HoaDon", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SaleManagement.DAL.HoaDon), true)]
[assembly: EdmRelationshipAttribute("SaleModel", "FK_lKien_LoaiLK", "LoaiLinhKien", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(SaleManagement.DAL.LoaiLinhKien), "LinhKien", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SaleManagement.DAL.LinhKien), true)]
[assembly: EdmRelationshipAttribute("SaleModel", "FK_lKienTon_lKien", "LinhKien", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(SaleManagement.DAL.LinhKien), "LinhKienTon", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SaleManagement.DAL.LinhKienTon), true)]

#endregion

namespace SaleManagement.DAL
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class SaleEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new SaleEntities object using the connection string found in the 'SaleEntities' section of the application configuration file.
        /// </summary>
        public SaleEntities() : base("name=SaleEntities", "SaleEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SaleEntities object.
        /// </summary>
        public SaleEntities(string connectionString) : base(connectionString, "SaleEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SaleEntities object.
        /// </summary>
        public SaleEntities(EntityConnection connection) : base(connection, "SaleEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ChiTietHoaDon> ChiTietHoaDons
        {
            get
            {
                if ((_ChiTietHoaDons == null))
                {
                    _ChiTietHoaDons = base.CreateObjectSet<ChiTietHoaDon>("ChiTietHoaDons");
                }
                return _ChiTietHoaDons;
            }
        }
        private ObjectSet<ChiTietHoaDon> _ChiTietHoaDons;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ChiTietPhieuNhap> ChiTietPhieuNhaps
        {
            get
            {
                if ((_ChiTietPhieuNhaps == null))
                {
                    _ChiTietPhieuNhaps = base.CreateObjectSet<ChiTietPhieuNhap>("ChiTietPhieuNhaps");
                }
                return _ChiTietPhieuNhaps;
            }
        }
        private ObjectSet<ChiTietPhieuNhap> _ChiTietPhieuNhaps;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<HoaDon> HoaDons
        {
            get
            {
                if ((_HoaDons == null))
                {
                    _HoaDons = base.CreateObjectSet<HoaDon>("HoaDons");
                }
                return _HoaDons;
            }
        }
        private ObjectSet<HoaDon> _HoaDons;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<KhachHang> KhachHangs
        {
            get
            {
                if ((_KhachHangs == null))
                {
                    _KhachHangs = base.CreateObjectSet<KhachHang>("KhachHangs");
                }
                return _KhachHangs;
            }
        }
        private ObjectSet<KhachHang> _KhachHangs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<LinhKien> LinhKiens
        {
            get
            {
                if ((_LinhKiens == null))
                {
                    _LinhKiens = base.CreateObjectSet<LinhKien>("LinhKiens");
                }
                return _LinhKiens;
            }
        }
        private ObjectSet<LinhKien> _LinhKiens;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<LinhKienTon> LinhKienTons
        {
            get
            {
                if ((_LinhKienTons == null))
                {
                    _LinhKienTons = base.CreateObjectSet<LinhKienTon>("LinhKienTons");
                }
                return _LinhKienTons;
            }
        }
        private ObjectSet<LinhKienTon> _LinhKienTons;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<LoaiLinhKien> LoaiLinhKiens
        {
            get
            {
                if ((_LoaiLinhKiens == null))
                {
                    _LoaiLinhKiens = base.CreateObjectSet<LoaiLinhKien>("LoaiLinhKiens");
                }
                return _LoaiLinhKiens;
            }
        }
        private ObjectSet<LoaiLinhKien> _LoaiLinhKiens;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<PhieuNhap> PhieuNhaps
        {
            get
            {
                if ((_PhieuNhaps == null))
                {
                    _PhieuNhaps = base.CreateObjectSet<PhieuNhap>("PhieuNhaps");
                }
                return _PhieuNhaps;
            }
        }
        private ObjectSet<PhieuNhap> _PhieuNhaps;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ChiTietHoaDons EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToChiTietHoaDons(ChiTietHoaDon chiTietHoaDon)
        {
            base.AddObject("ChiTietHoaDons", chiTietHoaDon);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ChiTietPhieuNhaps EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToChiTietPhieuNhaps(ChiTietPhieuNhap chiTietPhieuNhap)
        {
            base.AddObject("ChiTietPhieuNhaps", chiTietPhieuNhap);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the HoaDons EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToHoaDons(HoaDon hoaDon)
        {
            base.AddObject("HoaDons", hoaDon);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the KhachHangs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToKhachHangs(KhachHang khachHang)
        {
            base.AddObject("KhachHangs", khachHang);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the LinhKiens EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToLinhKiens(LinhKien linhKien)
        {
            base.AddObject("LinhKiens", linhKien);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the LinhKienTons EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToLinhKienTons(LinhKienTon linhKienTon)
        {
            base.AddObject("LinhKienTons", linhKienTon);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the LoaiLinhKiens EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToLoaiLinhKiens(LoaiLinhKien loaiLinhKien)
        {
            base.AddObject("LoaiLinhKiens", loaiLinhKien);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the PhieuNhaps EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPhieuNhaps(PhieuNhap phieuNhap)
        {
            base.AddObject("PhieuNhaps", phieuNhap);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SaleModel", Name="ChiTietHoaDon")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ChiTietHoaDon : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ChiTietHoaDon object.
        /// </summary>
        /// <param name="maHoaDon">Initial value of the MaHoaDon property.</param>
        /// <param name="id">Initial value of the ID property.</param>
        public static ChiTietHoaDon CreateChiTietHoaDon(global::System.String maHoaDon, global::System.Int32 id)
        {
            ChiTietHoaDon chiTietHoaDon = new ChiTietHoaDon();
            chiTietHoaDon.MaHoaDon = maHoaDon;
            chiTietHoaDon.ID = id;
            return chiTietHoaDon;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MaHoaDon
        {
            get
            {
                return _MaHoaDon;
            }
            set
            {
                if (_MaHoaDon != value)
                {
                    OnMaHoaDonChanging(value);
                    ReportPropertyChanging("MaHoaDon");
                    _MaHoaDon = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("MaHoaDon");
                    OnMaHoaDonChanged();
                }
            }
        }
        private global::System.String _MaHoaDon;
        partial void OnMaHoaDonChanging(global::System.String value);
        partial void OnMaHoaDonChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> SoLuongBan
        {
            get
            {
                return _SoLuongBan;
            }
            set
            {
                OnSoLuongBanChanging(value);
                ReportPropertyChanging("SoLuongBan");
                _SoLuongBan = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SoLuongBan");
                OnSoLuongBanChanged();
            }
        }
        private Nullable<global::System.Int32> _SoLuongBan;
        partial void OnSoLuongBanChanging(Nullable<global::System.Int32> value);
        partial void OnSoLuongBanChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> GiaSanPham
        {
            get
            {
                return _GiaSanPham;
            }
            set
            {
                OnGiaSanPhamChanging(value);
                ReportPropertyChanging("GiaSanPham");
                _GiaSanPham = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("GiaSanPham");
                OnGiaSanPhamChanged();
            }
        }
        private Nullable<global::System.Int32> _GiaSanPham;
        partial void OnGiaSanPhamChanging(Nullable<global::System.Int32> value);
        partial void OnGiaSanPhamChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SaleModel", "FK_cTietHDon_HoaDon", "HoaDon")]
        public HoaDon HoaDon
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<HoaDon>("SaleModel.FK_cTietHDon_HoaDon", "HoaDon").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<HoaDon>("SaleModel.FK_cTietHDon_HoaDon", "HoaDon").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<HoaDon> HoaDonReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<HoaDon>("SaleModel.FK_cTietHDon_HoaDon", "HoaDon");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<HoaDon>("SaleModel.FK_cTietHDon_HoaDon", "HoaDon", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SaleModel", "FK_cTietHDon_lKien", "LinhKien")]
        public LinhKien LinhKien
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<LinhKien>("SaleModel.FK_cTietHDon_lKien", "LinhKien").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<LinhKien>("SaleModel.FK_cTietHDon_lKien", "LinhKien").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<LinhKien> LinhKienReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<LinhKien>("SaleModel.FK_cTietHDon_lKien", "LinhKien");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<LinhKien>("SaleModel.FK_cTietHDon_lKien", "LinhKien", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SaleModel", Name="ChiTietPhieuNhap")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ChiTietPhieuNhap : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ChiTietPhieuNhap object.
        /// </summary>
        /// <param name="maPhieuNhap">Initial value of the MaPhieuNhap property.</param>
        /// <param name="id">Initial value of the ID property.</param>
        public static ChiTietPhieuNhap CreateChiTietPhieuNhap(global::System.String maPhieuNhap, global::System.Int32 id)
        {
            ChiTietPhieuNhap chiTietPhieuNhap = new ChiTietPhieuNhap();
            chiTietPhieuNhap.MaPhieuNhap = maPhieuNhap;
            chiTietPhieuNhap.ID = id;
            return chiTietPhieuNhap;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MaPhieuNhap
        {
            get
            {
                return _MaPhieuNhap;
            }
            set
            {
                if (_MaPhieuNhap != value)
                {
                    OnMaPhieuNhapChanging(value);
                    ReportPropertyChanging("MaPhieuNhap");
                    _MaPhieuNhap = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("MaPhieuNhap");
                    OnMaPhieuNhapChanged();
                }
            }
        }
        private global::System.String _MaPhieuNhap;
        partial void OnMaPhieuNhapChanging(global::System.String value);
        partial void OnMaPhieuNhapChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> SoLuongNhap
        {
            get
            {
                return _SoLuongNhap;
            }
            set
            {
                OnSoLuongNhapChanging(value);
                ReportPropertyChanging("SoLuongNhap");
                _SoLuongNhap = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SoLuongNhap");
                OnSoLuongNhapChanged();
            }
        }
        private Nullable<global::System.Int32> _SoLuongNhap;
        partial void OnSoLuongNhapChanging(Nullable<global::System.Int32> value);
        partial void OnSoLuongNhapChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> GiaNhap
        {
            get
            {
                return _GiaNhap;
            }
            set
            {
                OnGiaNhapChanging(value);
                ReportPropertyChanging("GiaNhap");
                _GiaNhap = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("GiaNhap");
                OnGiaNhapChanged();
            }
        }
        private Nullable<global::System.Int32> _GiaNhap;
        partial void OnGiaNhapChanging(Nullable<global::System.Int32> value);
        partial void OnGiaNhapChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SaleModel", "FK_cTietPNhap_lKien", "LinhKien")]
        public LinhKien LinhKien
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<LinhKien>("SaleModel.FK_cTietPNhap_lKien", "LinhKien").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<LinhKien>("SaleModel.FK_cTietPNhap_lKien", "LinhKien").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<LinhKien> LinhKienReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<LinhKien>("SaleModel.FK_cTietPNhap_lKien", "LinhKien");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<LinhKien>("SaleModel.FK_cTietPNhap_lKien", "LinhKien", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SaleModel", "FK_cTietPNhap_PhieuNhap", "PhieuNhap")]
        public PhieuNhap PhieuNhap
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PhieuNhap>("SaleModel.FK_cTietPNhap_PhieuNhap", "PhieuNhap").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PhieuNhap>("SaleModel.FK_cTietPNhap_PhieuNhap", "PhieuNhap").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<PhieuNhap> PhieuNhapReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PhieuNhap>("SaleModel.FK_cTietPNhap_PhieuNhap", "PhieuNhap");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<PhieuNhap>("SaleModel.FK_cTietPNhap_PhieuNhap", "PhieuNhap", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SaleModel", Name="HoaDon")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class HoaDon : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new HoaDon object.
        /// </summary>
        /// <param name="maHoaDon">Initial value of the MaHoaDon property.</param>
        /// <param name="maKH">Initial value of the MaKH property.</param>
        public static HoaDon CreateHoaDon(global::System.String maHoaDon, global::System.String maKH)
        {
            HoaDon hoaDon = new HoaDon();
            hoaDon.MaHoaDon = maHoaDon;
            hoaDon.MaKH = maKH;
            return hoaDon;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MaHoaDon
        {
            get
            {
                return _MaHoaDon;
            }
            set
            {
                if (_MaHoaDon != value)
                {
                    OnMaHoaDonChanging(value);
                    ReportPropertyChanging("MaHoaDon");
                    _MaHoaDon = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("MaHoaDon");
                    OnMaHoaDonChanged();
                }
            }
        }
        private global::System.String _MaHoaDon;
        partial void OnMaHoaDonChanging(global::System.String value);
        partial void OnMaHoaDonChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MaKH
        {
            get
            {
                return _MaKH;
            }
            set
            {
                OnMaKHChanging(value);
                ReportPropertyChanging("MaKH");
                _MaKH = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("MaKH");
                OnMaKHChanged();
            }
        }
        private global::System.String _MaKH;
        partial void OnMaKHChanging(global::System.String value);
        partial void OnMaKHChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> NgayLap
        {
            get
            {
                return _NgayLap;
            }
            set
            {
                OnNgayLapChanging(value);
                ReportPropertyChanging("NgayLap");
                _NgayLap = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NgayLap");
                OnNgayLapChanged();
            }
        }
        private Nullable<global::System.DateTime> _NgayLap;
        partial void OnNgayLapChanging(Nullable<global::System.DateTime> value);
        partial void OnNgayLapChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> NgayGiao
        {
            get
            {
                return _NgayGiao;
            }
            set
            {
                OnNgayGiaoChanging(value);
                ReportPropertyChanging("NgayGiao");
                _NgayGiao = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NgayGiao");
                OnNgayGiaoChanged();
            }
        }
        private Nullable<global::System.DateTime> _NgayGiao;
        partial void OnNgayGiaoChanging(Nullable<global::System.DateTime> value);
        partial void OnNgayGiaoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> TongGiaTien
        {
            get
            {
                return _TongGiaTien;
            }
            set
            {
                OnTongGiaTienChanging(value);
                ReportPropertyChanging("TongGiaTien");
                _TongGiaTien = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TongGiaTien");
                OnTongGiaTienChanged();
            }
        }
        private Nullable<global::System.Int32> _TongGiaTien;
        partial void OnTongGiaTienChanging(Nullable<global::System.Int32> value);
        partial void OnTongGiaTienChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DiaChiGiao
        {
            get
            {
                return _DiaChiGiao;
            }
            set
            {
                OnDiaChiGiaoChanging(value);
                ReportPropertyChanging("DiaChiGiao");
                _DiaChiGiao = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DiaChiGiao");
                OnDiaChiGiaoChanged();
            }
        }
        private global::System.String _DiaChiGiao;
        partial void OnDiaChiGiaoChanging(global::System.String value);
        partial void OnDiaChiGiaoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> TrangThai
        {
            get
            {
                return _TrangThai;
            }
            set
            {
                OnTrangThaiChanging(value);
                ReportPropertyChanging("TrangThai");
                _TrangThai = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TrangThai");
                OnTrangThaiChanged();
            }
        }
        private Nullable<global::System.Boolean> _TrangThai;
        partial void OnTrangThaiChanging(Nullable<global::System.Boolean> value);
        partial void OnTrangThaiChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GhiChu
        {
            get
            {
                return _GhiChu;
            }
            set
            {
                OnGhiChuChanging(value);
                ReportPropertyChanging("GhiChu");
                _GhiChu = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("GhiChu");
                OnGhiChuChanged();
            }
        }
        private global::System.String _GhiChu;
        partial void OnGhiChuChanging(global::System.String value);
        partial void OnGhiChuChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SaleModel", "FK_cTietHDon_HoaDon", "ChiTietHoaDon")]
        public EntityCollection<ChiTietHoaDon> ChiTietHoaDons
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ChiTietHoaDon>("SaleModel.FK_cTietHDon_HoaDon", "ChiTietHoaDon");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ChiTietHoaDon>("SaleModel.FK_cTietHDon_HoaDon", "ChiTietHoaDon", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SaleModel", "FK_HoaDon_kHang", "KhachHang")]
        public KhachHang KhachHang
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<KhachHang>("SaleModel.FK_HoaDon_kHang", "KhachHang").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<KhachHang>("SaleModel.FK_HoaDon_kHang", "KhachHang").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<KhachHang> KhachHangReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<KhachHang>("SaleModel.FK_HoaDon_kHang", "KhachHang");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<KhachHang>("SaleModel.FK_HoaDon_kHang", "KhachHang", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SaleModel", Name="KhachHang")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class KhachHang : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new KhachHang object.
        /// </summary>
        /// <param name="maKH">Initial value of the MaKH property.</param>
        public static KhachHang CreateKhachHang(global::System.String maKH)
        {
            KhachHang khachHang = new KhachHang();
            khachHang.MaKH = maKH;
            return khachHang;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MaKH
        {
            get
            {
                return _MaKH;
            }
            set
            {
                if (_MaKH != value)
                {
                    OnMaKHChanging(value);
                    ReportPropertyChanging("MaKH");
                    _MaKH = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("MaKH");
                    OnMaKHChanged();
                }
            }
        }
        private global::System.String _MaKH;
        partial void OnMaKHChanging(global::System.String value);
        partial void OnMaKHChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TenKH
        {
            get
            {
                return _TenKH;
            }
            set
            {
                OnTenKHChanging(value);
                ReportPropertyChanging("TenKH");
                _TenKH = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TenKH");
                OnTenKHChanged();
            }
        }
        private global::System.String _TenKH;
        partial void OnTenKHChanging(global::System.String value);
        partial void OnTenKHChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TenDN
        {
            get
            {
                return _TenDN;
            }
            set
            {
                OnTenDNChanging(value);
                ReportPropertyChanging("TenDN");
                _TenDN = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TenDN");
                OnTenDNChanged();
            }
        }
        private global::System.String _TenDN;
        partial void OnTenDNChanging(global::System.String value);
        partial void OnTenDNChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MatKhau
        {
            get
            {
                return _MatKhau;
            }
            set
            {
                OnMatKhauChanging(value);
                ReportPropertyChanging("MatKhau");
                _MatKhau = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MatKhau");
                OnMatKhauChanged();
            }
        }
        private global::System.String _MatKhau;
        partial void OnMatKhauChanging(global::System.String value);
        partial void OnMatKhauChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DiaChi
        {
            get
            {
                return _DiaChi;
            }
            set
            {
                OnDiaChiChanging(value);
                ReportPropertyChanging("DiaChi");
                _DiaChi = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DiaChi");
                OnDiaChiChanged();
            }
        }
        private global::System.String _DiaChi;
        partial void OnDiaChiChanging(global::System.String value);
        partial void OnDiaChiChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SDT
        {
            get
            {
                return _SDT;
            }
            set
            {
                OnSDTChanging(value);
                ReportPropertyChanging("SDT");
                _SDT = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SDT");
                OnSDTChanged();
            }
        }
        private global::System.String _SDT;
        partial void OnSDTChanging(global::System.String value);
        partial void OnSDTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SaleModel", "FK_HoaDon_kHang", "HoaDon")]
        public EntityCollection<HoaDon> HoaDons
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<HoaDon>("SaleModel.FK_HoaDon_kHang", "HoaDon");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<HoaDon>("SaleModel.FK_HoaDon_kHang", "HoaDon", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SaleModel", Name="LinhKien")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class LinhKien : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new LinhKien object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="maLKien">Initial value of the MaLKien property.</param>
        public static LinhKien CreateLinhKien(global::System.Int32 id, global::System.String maLKien)
        {
            LinhKien linhKien = new LinhKien();
            linhKien.ID = id;
            linhKien.MaLKien = maLKien;
            return linhKien;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MaLKien
        {
            get
            {
                return _MaLKien;
            }
            set
            {
                OnMaLKienChanging(value);
                ReportPropertyChanging("MaLKien");
                _MaLKien = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("MaLKien");
                OnMaLKienChanged();
            }
        }
        private global::System.String _MaLKien;
        partial void OnMaLKienChanging(global::System.String value);
        partial void OnMaLKienChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TenLinhKien
        {
            get
            {
                return _TenLinhKien;
            }
            set
            {
                OnTenLinhKienChanging(value);
                ReportPropertyChanging("TenLinhKien");
                _TenLinhKien = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TenLinhKien");
                OnTenLinhKienChanged();
            }
        }
        private global::System.String _TenLinhKien;
        partial void OnTenLinhKienChanging(global::System.String value);
        partial void OnTenLinhKienChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MaLoai
        {
            get
            {
                return _MaLoai;
            }
            set
            {
                OnMaLoaiChanging(value);
                ReportPropertyChanging("MaLoai");
                _MaLoai = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MaLoai");
                OnMaLoaiChanged();
            }
        }
        private global::System.String _MaLoai;
        partial void OnMaLoaiChanging(global::System.String value);
        partial void OnMaLoaiChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> GiaBan
        {
            get
            {
                return _GiaBan;
            }
            set
            {
                OnGiaBanChanging(value);
                ReportPropertyChanging("GiaBan");
                _GiaBan = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("GiaBan");
                OnGiaBanChanged();
            }
        }
        private Nullable<global::System.Int32> _GiaBan;
        partial void OnGiaBanChanging(Nullable<global::System.Int32> value);
        partial void OnGiaBanChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] HinhAnh
        {
            get
            {
                return StructuralObject.GetValidValue(_HinhAnh);
            }
            set
            {
                OnHinhAnhChanging(value);
                ReportPropertyChanging("HinhAnh");
                _HinhAnh = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("HinhAnh");
                OnHinhAnhChanged();
            }
        }
        private global::System.Byte[] _HinhAnh;
        partial void OnHinhAnhChanging(global::System.Byte[] value);
        partial void OnHinhAnhChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> SanPhamMoi
        {
            get
            {
                return _SanPhamMoi;
            }
            set
            {
                OnSanPhamMoiChanging(value);
                ReportPropertyChanging("SanPhamMoi");
                _SanPhamMoi = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SanPhamMoi");
                OnSanPhamMoiChanged();
            }
        }
        private Nullable<global::System.Boolean> _SanPhamMoi;
        partial void OnSanPhamMoiChanging(Nullable<global::System.Boolean> value);
        partial void OnSanPhamMoiChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ThongTinThem
        {
            get
            {
                return _ThongTinThem;
            }
            set
            {
                OnThongTinThemChanging(value);
                ReportPropertyChanging("ThongTinThem");
                _ThongTinThem = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ThongTinThem");
                OnThongTinThemChanged();
            }
        }
        private global::System.String _ThongTinThem;
        partial void OnThongTinThemChanging(global::System.String value);
        partial void OnThongTinThemChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SaleModel", "FK_cTietHDon_lKien", "ChiTietHoaDon")]
        public EntityCollection<ChiTietHoaDon> ChiTietHoaDons
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ChiTietHoaDon>("SaleModel.FK_cTietHDon_lKien", "ChiTietHoaDon");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ChiTietHoaDon>("SaleModel.FK_cTietHDon_lKien", "ChiTietHoaDon", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SaleModel", "FK_cTietPNhap_lKien", "ChiTietPhieuNhap")]
        public EntityCollection<ChiTietPhieuNhap> ChiTietPhieuNhaps
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ChiTietPhieuNhap>("SaleModel.FK_cTietPNhap_lKien", "ChiTietPhieuNhap");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ChiTietPhieuNhap>("SaleModel.FK_cTietPNhap_lKien", "ChiTietPhieuNhap", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SaleModel", "FK_lKien_LoaiLK", "LoaiLinhKien")]
        public LoaiLinhKien LoaiLinhKien
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<LoaiLinhKien>("SaleModel.FK_lKien_LoaiLK", "LoaiLinhKien").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<LoaiLinhKien>("SaleModel.FK_lKien_LoaiLK", "LoaiLinhKien").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<LoaiLinhKien> LoaiLinhKienReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<LoaiLinhKien>("SaleModel.FK_lKien_LoaiLK", "LoaiLinhKien");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<LoaiLinhKien>("SaleModel.FK_lKien_LoaiLK", "LoaiLinhKien", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SaleModel", "FK_lKienTon_lKien", "LinhKienTon")]
        public EntityCollection<LinhKienTon> LinhKienTons
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<LinhKienTon>("SaleModel.FK_lKienTon_lKien", "LinhKienTon");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<LinhKienTon>("SaleModel.FK_lKienTon_lKien", "LinhKienTon", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SaleModel", Name="LinhKienTon")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class LinhKienTon : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new LinhKienTon object.
        /// </summary>
        /// <param name="idTon">Initial value of the idTon property.</param>
        /// <param name="ngay">Initial value of the Ngay property.</param>
        public static LinhKienTon CreateLinhKienTon(global::System.Int32 idTon, global::System.DateTime ngay)
        {
            LinhKienTon linhKienTon = new LinhKienTon();
            linhKienTon.idTon = idTon;
            linhKienTon.Ngay = ngay;
            return linhKienTon;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idTon
        {
            get
            {
                return _idTon;
            }
            set
            {
                if (_idTon != value)
                {
                    OnidTonChanging(value);
                    ReportPropertyChanging("idTon");
                    _idTon = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idTon");
                    OnidTonChanged();
                }
            }
        }
        private global::System.Int32 _idTon;
        partial void OnidTonChanging(global::System.Int32 value);
        partial void OnidTonChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Ngay
        {
            get
            {
                return _Ngay;
            }
            set
            {
                OnNgayChanging(value);
                ReportPropertyChanging("Ngay");
                _Ngay = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Ngay");
                OnNgayChanged();
            }
        }
        private global::System.DateTime _Ngay;
        partial void OnNgayChanging(global::System.DateTime value);
        partial void OnNgayChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ID
        {
            get
            {
                return _ID;
            }
            set
            {
                OnIDChanging(value);
                ReportPropertyChanging("ID");
                _ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ID");
                OnIDChanged();
            }
        }
        private Nullable<global::System.Int32> _ID;
        partial void OnIDChanging(Nullable<global::System.Int32> value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> SoLuongTon
        {
            get
            {
                return _SoLuongTon;
            }
            set
            {
                OnSoLuongTonChanging(value);
                ReportPropertyChanging("SoLuongTon");
                _SoLuongTon = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SoLuongTon");
                OnSoLuongTonChanged();
            }
        }
        private Nullable<global::System.Int32> _SoLuongTon;
        partial void OnSoLuongTonChanging(Nullable<global::System.Int32> value);
        partial void OnSoLuongTonChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SaleModel", "FK_lKienTon_lKien", "LinhKien")]
        public LinhKien LinhKien
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<LinhKien>("SaleModel.FK_lKienTon_lKien", "LinhKien").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<LinhKien>("SaleModel.FK_lKienTon_lKien", "LinhKien").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<LinhKien> LinhKienReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<LinhKien>("SaleModel.FK_lKienTon_lKien", "LinhKien");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<LinhKien>("SaleModel.FK_lKienTon_lKien", "LinhKien", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SaleModel", Name="LoaiLinhKien")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class LoaiLinhKien : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new LoaiLinhKien object.
        /// </summary>
        /// <param name="maLoai">Initial value of the MaLoai property.</param>
        public static LoaiLinhKien CreateLoaiLinhKien(global::System.String maLoai)
        {
            LoaiLinhKien loaiLinhKien = new LoaiLinhKien();
            loaiLinhKien.MaLoai = maLoai;
            return loaiLinhKien;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MaLoai
        {
            get
            {
                return _MaLoai;
            }
            set
            {
                if (_MaLoai != value)
                {
                    OnMaLoaiChanging(value);
                    ReportPropertyChanging("MaLoai");
                    _MaLoai = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("MaLoai");
                    OnMaLoaiChanged();
                }
            }
        }
        private global::System.String _MaLoai;
        partial void OnMaLoaiChanging(global::System.String value);
        partial void OnMaLoaiChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TenLoai
        {
            get
            {
                return _TenLoai;
            }
            set
            {
                OnTenLoaiChanging(value);
                ReportPropertyChanging("TenLoai");
                _TenLoai = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TenLoai");
                OnTenLoaiChanged();
            }
        }
        private global::System.String _TenLoai;
        partial void OnTenLoaiChanging(global::System.String value);
        partial void OnTenLoaiChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MoTa
        {
            get
            {
                return _MoTa;
            }
            set
            {
                OnMoTaChanging(value);
                ReportPropertyChanging("MoTa");
                _MoTa = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MoTa");
                OnMoTaChanged();
            }
        }
        private global::System.String _MoTa;
        partial void OnMoTaChanging(global::System.String value);
        partial void OnMoTaChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SaleModel", "FK_lKien_LoaiLK", "LinhKien")]
        public EntityCollection<LinhKien> LinhKiens
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<LinhKien>("SaleModel.FK_lKien_LoaiLK", "LinhKien");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<LinhKien>("SaleModel.FK_lKien_LoaiLK", "LinhKien", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SaleModel", Name="PhieuNhap")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PhieuNhap : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PhieuNhap object.
        /// </summary>
        /// <param name="maPhieuNhap">Initial value of the MaPhieuNhap property.</param>
        public static PhieuNhap CreatePhieuNhap(global::System.String maPhieuNhap)
        {
            PhieuNhap phieuNhap = new PhieuNhap();
            phieuNhap.MaPhieuNhap = maPhieuNhap;
            return phieuNhap;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MaPhieuNhap
        {
            get
            {
                return _MaPhieuNhap;
            }
            set
            {
                if (_MaPhieuNhap != value)
                {
                    OnMaPhieuNhapChanging(value);
                    ReportPropertyChanging("MaPhieuNhap");
                    _MaPhieuNhap = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("MaPhieuNhap");
                    OnMaPhieuNhapChanged();
                }
            }
        }
        private global::System.String _MaPhieuNhap;
        partial void OnMaPhieuNhapChanging(global::System.String value);
        partial void OnMaPhieuNhapChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> NgayLap
        {
            get
            {
                return _NgayLap;
            }
            set
            {
                OnNgayLapChanging(value);
                ReportPropertyChanging("NgayLap");
                _NgayLap = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NgayLap");
                OnNgayLapChanged();
            }
        }
        private Nullable<global::System.DateTime> _NgayLap;
        partial void OnNgayLapChanging(Nullable<global::System.DateTime> value);
        partial void OnNgayLapChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GhiChu
        {
            get
            {
                return _GhiChu;
            }
            set
            {
                OnGhiChuChanging(value);
                ReportPropertyChanging("GhiChu");
                _GhiChu = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("GhiChu");
                OnGhiChuChanged();
            }
        }
        private global::System.String _GhiChu;
        partial void OnGhiChuChanging(global::System.String value);
        partial void OnGhiChuChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SaleModel", "FK_cTietPNhap_PhieuNhap", "ChiTietPhieuNhap")]
        public EntityCollection<ChiTietPhieuNhap> ChiTietPhieuNhaps
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ChiTietPhieuNhap>("SaleModel.FK_cTietPNhap_PhieuNhap", "ChiTietPhieuNhap");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ChiTietPhieuNhap>("SaleModel.FK_cTietPNhap_PhieuNhap", "ChiTietPhieuNhap", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
